export const DEFAULT_WRITE_DELAY_MS = 1000

export const DEFAULT_TERMINAL_OUTPUT_CHARACTER_LIMIT = 50_000

export const MIN_CHECKPOINT_TIMEOUT_SECONDS = 10

export const MAX_CHECKPOINT_TIMEOUT_SECONDS = 60

export const DEFAULT_CHECKPOINT_TIMEOUT_SECONDS = 15

export const DEFAULT_CONSECUTIVE_MISTAKE_LIMIT = 3
