// Core modules
export * from "./api.js"
export * from "./codebase-index.js"
export * from "./checkpoint.js"
export * from "./context-management.js"
export * from "./context-mentions.js"
export * from "./cookie-consent.js"
export * from "./custom-tool.js"
export * from "./errors/index.js"
export * from "./events.js"
export * from "./experiment.js"
export * from "./followup.js"
export * from "./git.js"
export * from "./global-settings.js"
export * from "./history.js"
export * from "./image-generation.js"
export * from "./ipc.js"
export * from "./mcp.js"
export * from "./message.js"
export * from "./mode.js"
export * from "./model.js"
export * from "./provider-settings/index.js"
export * from "./task.js"
export * from "./todo.js"
export * from "./skills.js"
export * from "./terminal.js"
export * from "./language.js"
export * from "./tool.js"
export * from "./tool-params.js"
export * from "./vscode.js"
export * from "./worktree.js"

// Refactored modules (new directory structure)
export * from "./embedding/index.js"
export * from "./streaming/index.js"
export * from "./vscode-extension-host/index.js"